name: github-action-docker-project

on: push
env:
    IMAGE_NAME: "myapp"
    IMAGE_TAG: "${env.BUILD_NUMBER}"
    CONTAINER_NAME: "myapp-container"
jobs:
  job1:
    name: docker deployment
    runs-on: ubuntu:latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
    steps: 
        - name: build docker IMAGE_NAME
          run: docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    steps:
        - nume: run docker container
          run: docker run -d --name ${CONTAINER_NAME} -p 80:80 ${IMAGE_NAME}:${IMAGE_TAG}
    steps: 
        - name: print message
          run: echo "succsssfull"
    